---
title: "AS Description"
author: "Ilya Ilin"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    number_sections: false
    theme: cerulean
    highlight: tango
---

### Step 1 - Baseline classification

182 Climate-specific, 1917 Green non-climate, 12866 Not climate-specific, not green.

#### Climate-specific

False positives examples: ST0027-S1, ST0384-S12, ST0492, ST0621.

Interesting cases: ST0393-S17

#### Green non-climate

Cases like ST0092 and ST0289 should arguably be Climate-specific.

Some false positives examples: ST0173, ST0191 and ST0194.

### Step 2 - Further classification

The dataset does **not** show unique pairs. Each skill can have up to 5 associated classifications, if all the runs disagree. Firstly, select *non-tied* max for runs agreeing (which leaves only **2-2 cases** - 10 total skills). This leaves **2099** skills because ST0504 S13 had 6 runs for some reason.

- 2859 rows here, though only 2099 Standard Skill pairs exist.
- 2099/14966 skills classified as somewhat related to low carbon/green skills.
- 495 cases of "Error: Processing failed".

Next, filter out "Not-climate-nor-green-related", "Error: Processing failed" and `slice_max()` to get **580** skills.

It also seems that the skills classified as "Environmental-protection", "Waste-management", "Climate-adaptation", "Sustainability" and "Forestry-ecosystem-management" are not closely related to low-carbon.

Identifies **78** skills after filtering out the above classes, with tricky cases like ST0155-S18.
