---
title: "AS Description"
author: "Ilya Ilin"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    number_sections: false
    theme: cerulean
    highlight: tango
---

### Obtaining Classification

Using Aurelien's classification, keep low carbon skills in Decarbonization-Industry, Buildings, Transport, and Energy. Also keep Climate CCS and possibly Climate-general.

After manual check in Excel, get the full skills classification.

### `AS-1-Assignment.R`

Simply create a full list of AS skills with tags to identify as low carbon or not. Additionally, classify standards as low carbon, with standard-level skills content.

### `AS-2-SOC.R`

Using the assigned classification from, obtain the crosswalk between low carbon standards and their SOC occupations, manually verifying the low carbon classification from the `.pdf` guidelines.

#### Notes

There are 39 (40 observations because 1 standard is double counted) low carbon standards, and 46 crosswalked items (to do with multiple versions of the file). After taking the most recent version, 39 items remain.

After manually checking the classification, there are **16** inconsistencies.




